{{ if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-green
spec:
  selector:
    matchLabels:
      slot: green
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        slot: green
    spec:
      containers:
      - name: {{ .Values.app.container.name }}-green
        image: shubh228/flask-app:v3
        ports:
        - containerPort: {{ .Values.app.container.containerPort }}
{{ end }}

