apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisservice.name }}
  namespace: {{ .Values.target }}
spec:
  ports:
    - port: {{ .Values.redisservice.port }}
      protocol: {{ .Values.redisservice.protocol }}
      targetPort: {{ .Values.redis.container.containerPort }}
  selector:
    app: redis
  type: {{ .Values.redisservice.type }}

