green:
  enabled: false

blue:
  enabled: false

replicaCount: 1
productionSlot: blue

flask:
  name: flask
  container:
     name: my-flask-app
     containerPort: 5000

service:
  type: NodePort
  port: 5000
  protocol: TCP
  name: flask-svc
