apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-task6
  namespace: {{ .Values.target }}
spec:
  selector:
    matchLabels:
      app: flask
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: {{ .Values.app.container.name }}-task6
        image: {{ .Values.app.container.image }}
        ports:
        - containerPort: {{ .Values.app.container.containerPort }}

