apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appservice.name }}-task6
  namespace: {{ .Values.target }}
spec:
  ports:
   -  port: {{ .Values.appservice.port }}
      protocol: {{ .Values.appservice.protocol }}
      targetPort: {{ .Values.app.container.containerPort }}
  selector:
    app: flask
  type: {{ .Values.appservice.type }}

