apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-task6
  namespace: {{ .Values.target }}
spec:
  ports:
   -  port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.flask.container.containerPort }}
  selector:
    slot: blue
  type: {{ .Values.service.type }}

