
replicaCount: 4
target: default
flask:
  name: flask
  container:
     name: my-flask-app
     image: shubh228/flask-app:v2
     containerPort: 5000

service:
  type: NodePort
  port: 5000
  protocol: TCP
  name: flask-svc

